"""FreeSWITCH dialplan XML generator.

Generates the public-sip.xml dialplan from PBX configuration stored in the
database. The dialplan has three contexts:

1. public   — internal extension routing, VVP loopback, outbound, inbound PSTN
2. redirected — handles 302 from signing service, routes to verification
3. verified — handles 302 from verification, delivers to extension with brand headers

Only the public context has dynamic parts (API key, extensions, caller ID).
The redirected and verified contexts use generic regexes and are static.
"""

import json
import logging
from xml.sax.saxutils import escape as xml_escape

from app.api.models import PBXExtension

log = logging.getLogger(__name__)


def _parse_extensions(extensions_json: str) -> list[PBXExtension]:
    """Parse extensions JSON string into PBXExtension objects."""
    try:
        raw = json.loads(extensions_json)
        return [PBXExtension(**e) for e in raw]
    except (json.JSONDecodeError, TypeError, ValueError):
        return []


def generate_dialplan(
    api_key_value: str | None,
    extensions_json: str,
    default_caller_id: str = "+441923311000",
) -> str:
    """Generate FreeSWITCH dialplan XML from PBX configuration.

    Args:
        api_key_value: Raw API key for X-VVP-API-Key header (None = no key)
        extensions_json: JSON array of extension configs
        default_caller_id: E.164 caller ID for VVP loopback calls

    Returns:
        Complete XML dialplan string
    """
    extensions = _parse_extensions(extensions_json)
    enabled_extensions = sorted(
        [e for e in extensions if e.enabled], key=lambda e: e.ext
    )

    api_key_line = ""
    if api_key_value:
        api_key_line = (
            f'        <action application="export" '
            f'data="nolocal:sip_h_X-VVP-API-Key={xml_escape(api_key_value)}"/>'
        )

    # Build VVP inbound extension blocks for each enabled extension
    inbound_blocks = _generate_inbound_blocks(enabled_extensions)

    xml = f"""\
<?xml version="1.0" encoding="utf-8"?>
<!--
  VVP Dialplan - Generated by PBX Management UI

  Extensions: {', '.join(str(e.ext) for e in enabled_extensions) or 'none configured'}
  API Key: {'configured' if api_key_value else 'NOT SET'}
  Default Caller ID: {default_caller_id}

  File: /etc/freeswitch/dialplan/public.xml

  After updating, reload dialplan:
    fs_cli -x "reloadxml"
-->
<include>
  <context name="public">

    <!-- Internal extension dialing (1001-1099) - direct, no VVP -->
    <extension name="internal-extensions">
      <condition field="${{sofia_profile_name}}" expression="^internal$"/>
      <condition field="destination_number" expression="^(10\\d{{2}})$">
        <action application="log" data="INFO [VVP] Internal call to extension $1"/>
        <action application="set" data="hangup_after_bridge=true"/>
        <action application="bridge" data="user/$1@pbx.rcnx.io"/>
      </condition>
    </extension>

    <!-- VVP Loopback Test: 7 + extension -> signing -> verification -> extension -->
    <extension name="vvp-loopback-outbound">
      <!-- Match internal SIP profile OR loopback channels (empty profile name for fs_cli originate) -->
      <condition field="${{sofia_profile_name}}" expression="^(internal)?$"/>
      <condition field="destination_number" expression="^7(10\\d{{2}})$">
        <action application="log" data="INFO [VVP] Loopback call to extension $1 via VVP signing"/>
        <action application="set" data="hangup_after_bridge=true"/>
        <action application="set" data="continue_on_fail=true"/>
        <!-- Allow 30s for signing service (TN lookup + VVP create can take 5-15s) -->
        <action application="set" data="bridge_timeout=30"/>
        <action application="set" data="progress_timeout=30"/>
        <!-- SIP Timer B: max wait for INVITE transaction (default 32s, extend to 35s) -->
        <action application="set" data="sip_invite_timeout=35"/>
        <!-- Map extension to test TN: dest from dialed digits, caller is configured CLI -->
        <action application="set" data="loopback_dest_tn=+44192331$1"/>
        <action application="set" data="effective_caller_id_number={xml_escape(default_caller_id)}"/>
        <action application="set" data="effective_caller_id_name=VVP Loopback"/>
        <!-- Route signing 302 through redirected context (not directly to Contact URI) -->
        <action application="set" data="sip_redirect_context=redirected"/>
        <!-- Route through signing service with org API key -->
{api_key_line}
        <action application="log" data="INFO [VVP] Routing to signing service: ${{loopback_dest_tn}}"/>
        <action application="bridge" data="sofia/external/${{loopback_dest_tn}}@127.0.0.1:5070"/>
      </condition>
    </extension>

    <!-- VVP Loopback Inbound: calls from verification service with VVP headers -->
    <extension name="vvp-loopback-inbound">
      <condition field="${{sofia_profile_name}}" expression="^external$"/>
      <condition field="destination_number" expression="^\\+?4419233110(\\d{{2}})$">
        <action application="log" data="INFO [VVP] Loopback inbound for extension 10$1"/>
        <!-- Extract VVP headers from 302 response (sip_rh_*) or INVITE (sip_h_*) -->
        <action application="set" data="vvp_brand_name=${{sip_rh_X-VVP-Brand-Name}}"/>
        <action application="set" data="vvp_brand_logo=${{sip_rh_X-VVP-Brand-Logo}}"/>
        <action application="set" data="vvp_status=${{sip_rh_X-VVP-Status}}"/>
        <!-- Fallback to request headers if response headers not available -->
        <action application="set" data="vvp_brand_name=${{vvp_brand_name:${{sip_h_X-VVP-Brand-Name}}}}"/>
        <action application="set" data="vvp_brand_logo=${{vvp_brand_logo:${{sip_h_X-VVP-Brand-Logo}}}}"/>
        <action application="set" data="vvp_status=${{vvp_status:${{sip_h_X-VVP-Status}}}}"/>
        <!-- URL decode -->
        <action application="set" data="vvp_brand_name=${{url_decode(${{vvp_brand_name}})}}"/>
        <action application="set" data="vvp_brand_logo=${{url_decode(${{vvp_brand_logo}})}}"/>
        <action application="log" data="INFO [VVP] Loopback: brand=${{vvp_brand_name}}, status=${{vvp_status}}"/>
        <!-- Export to B-leg for WebRTC client -->
        <action application="export" data="nolocal:sip_h_X-VVP-Brand-Name=${{vvp_brand_name}}"/>
        <action application="export" data="nolocal:sip_h_X-VVP-Brand-Logo=${{vvp_brand_logo}}"/>
        <action application="export" data="nolocal:sip_h_X-VVP-Status=${{vvp_status}}"/>
        <action application="ring_ready"/>
        <action application="set" data="hangup_after_bridge=true"/>
        <!-- Bridge to destination extension -->
        <action application="set" data="target_ext=10$1"/>
        <action application="bridge" data="user/${{target_ext}}@pbx.rcnx.io"/>
      </condition>
    </extension>

    <!-- UK Outbound: 9 + 0 + UK number -> Twilio gateway -->
    <extension name="uk-outbound-9prefix">
      <condition field="${{sofia_profile_name}}" expression="^internal$"/>
      <condition field="destination_number" expression="^90(\\d{{9,11}})$">
        <action application="log" data="INFO [VVP] UK Outbound: dialing +44$1 via Twilio"/>
        <action application="export" data="call_direction=outbound"/>
        <action application="set" data="hangup_after_bridge=true"/>
        <action application="set" data="continue_on_fail=true"/>
        <!-- Set valid caller ID for Twilio -->
        <action application="set" data="effective_caller_id_number={xml_escape(default_caller_id)}"/>
        <action application="set" data="effective_caller_id_name=VVP Test"/>
        <action application="bridge" data="sofia/gateway/7d3b7bf4-e1e7-43f0-8d6c-5dd4eb6e35cc/+44$1"/>
      </condition>
    </extension>

    <!-- International Outbound: 9 + 00 + country code + number -->
    <extension name="intl-outbound-9prefix">
      <condition field="${{sofia_profile_name}}" expression="^internal$"/>
      <condition field="destination_number" expression="^900(\\d{{10,15}})$">
        <action application="log" data="INFO [VVP] Intl Outbound: dialing +$1 via Twilio"/>
        <action application="export" data="call_direction=outbound"/>
        <action application="set" data="hangup_after_bridge=true"/>
        <action application="set" data="continue_on_fail=true"/>
        <!-- Set valid caller ID for Twilio -->
        <action application="set" data="effective_caller_id_number={xml_escape(default_caller_id)}"/>
        <action application="set" data="effective_caller_id_name=VVP Test"/>
        <action application="bridge" data="sofia/gateway/7d3b7bf4-e1e7-43f0-8d6c-5dd4eb6e35cc/+$1"/>
      </condition>
    </extension>

{inbound_blocks}
    <!-- Fallback for unmatched internal calls -->
    <extension name="internal-unmatched">
      <condition field="${{sofia_profile_name}}" expression="^internal$">
        <action application="log" data="WARNING [VVP] Unmatched internal call to ${{destination_number}}"/>
        <action application="playback" data="ivr/ivr-call_cannot_be_completed_as_dialed.wav"/>
        <action application="hangup" data="NO_ROUTE_DESTINATION"/>
      </condition>
    </extension>

  </context>

  <!-- Redirected context: handles calls after 302 redirect from signing service -->
  <context name="redirected">

    <!-- VVP Redirect: signing 302 -> verification service -> extension -->
    <extension name="vvp-redirect-to-verify">
      <condition field="destination_number" expression="^\\+?44192331(\\d{{4}})$">
        <action application="log" data="INFO [VVP] Signing 302 redirect for +44192331$1 — routing to verification"/>
        <!-- Extract STIR attestation headers from signing 302 response -->
        <action application="set" data="vvp_identity_hdr=${{sip_rh_Identity}}"/>
        <action application="set" data="vvp_identity=${{sip_rh_P-VVP-Identity}}"/>
        <action application="set" data="vvp_passport=${{sip_rh_P-VVP-Passport}}"/>
        <action application="log" data="INFO [VVP] Signing result: Identity=${{vvp_identity_hdr:+yes:no}}, Passport=${{vvp_passport:+yes:no}}"/>
        <!-- Forward STIR attestation headers to verification service -->
        <action application="export" data="nolocal:sip_h_Identity=${{vvp_identity_hdr}}"/>
        <action application="export" data="nolocal:sip_h_P-VVP-Identity=${{vvp_identity}}"/>
        <action application="export" data="nolocal:sip_h_P-VVP-Passport=${{vvp_passport}}"/>
        <!-- When verification returns 302, route to verified context for delivery -->
        <action application="export" data="sip_redirect_context=verified"/>
        <action application="set" data="hangup_after_bridge=true"/>
        <action application="set" data="continue_on_fail=true"/>
        <action application="set" data="bridge_timeout=30"/>
        <action application="set" data="sip_invite_timeout=35"/>
        <action application="log" data="INFO [VVP] Bridging to verification service at 127.0.0.1:5071"/>
        <action application="bridge" data="sofia/external/${{destination_number}}@127.0.0.1:5071"/>
      </condition>
    </extension>

    <!-- Fallback for unmatched redirects -->
    <extension name="redirect-unmatched">
      <condition field="destination_number" expression=".*">
        <action application="log" data="WARNING [VVP] Unmatched redirect to ${{destination_number}}"/>
        <action application="hangup" data="NO_ROUTE_DESTINATION"/>
      </condition>
    </extension>

  </context>

  <!-- Verified context: delivers call to extension after verification 302 -->
  <context name="verified">

    <!-- Deliver verified call to destination extension -->
    <extension name="vvp-deliver">
      <condition field="destination_number" expression="^\\+?4419233110(\\d{{2}})$">
        <action application="log" data="INFO [VVP] Verification complete — delivering to extension 10$1"/>
        <!-- Extract VVP headers from verification 302 response -->
        <action application="set" data="vvp_brand_name=${{sip_rh_X-VVP-Brand-Name}}"/>
        <action application="set" data="vvp_brand_logo=${{sip_rh_X-VVP-Brand-Logo}}"/>
        <action application="set" data="vvp_status=${{sip_rh_X-VVP-Status}}"/>
        <!-- Fallback to request headers -->
        <action application="set" data="vvp_brand_name=${{vvp_brand_name:${{sip_h_X-VVP-Brand-Name}}}}"/>
        <action application="set" data="vvp_brand_logo=${{vvp_brand_logo:${{sip_h_X-VVP-Brand-Logo}}}}"/>
        <action application="set" data="vvp_status=${{vvp_status:${{sip_h_X-VVP-Status}}}}"/>
        <!-- URL decode -->
        <action application="set" data="vvp_brand_name=${{url_decode(${{vvp_brand_name}})}}"/>
        <action application="set" data="vvp_brand_logo=${{url_decode(${{vvp_brand_logo}})}}"/>
        <action application="log" data="INFO [VVP] Delivering: brand=${{vvp_brand_name}}, status=${{vvp_status}}"/>
        <!-- Export VVP headers to B-leg for WebRTC client -->
        <action application="export" data="nolocal:sip_h_X-VVP-Brand-Name=${{vvp_brand_name}}"/>
        <action application="export" data="nolocal:sip_h_X-VVP-Brand-Logo=${{vvp_brand_logo}}"/>
        <action application="export" data="nolocal:sip_h_X-VVP-Status=${{vvp_status}}"/>
        <action application="ring_ready"/>
        <action application="set" data="hangup_after_bridge=true"/>
        <action application="set" data="target_ext=10$1"/>
        <action application="bridge" data="user/${{target_ext}}@pbx.rcnx.io"/>
      </condition>
    </extension>

    <!-- Fallback for unmatched verified calls -->
    <extension name="verified-unmatched">
      <condition field="destination_number" expression=".*">
        <action application="log" data="WARNING [VVP] Unmatched verified call to ${{destination_number}}"/>
        <action application="hangup" data="NO_ROUTE_DESTINATION"/>
      </condition>
    </extension>

  </context>
</include>
"""
    return xml


def _generate_inbound_blocks(enabled_extensions: list[PBXExtension]) -> str:
    """Generate VVP inbound extension blocks for the public context.

    Each enabled extension gets a specific inbound block matching its TN.
    The last extension in the list becomes the catch-all default for
    unmatched external inbound calls.
    """
    if not enabled_extensions:
        return """\
    <!-- No extensions configured — inbound calls will fall through to unmatched -->
"""

    blocks = []

    # Specific inbound blocks for each extension (except last which is catch-all)
    for i, ext in enumerate(enabled_extensions):
        is_last = i == len(enabled_extensions) - 1
        # Extract the 2-digit suffix from cli for TN matching
        # e.g., +441923311006 -> 06 suffix, matches extension 1006
        ext_suffix = f"{ext.ext:04d}"[-2:]  # Last 2 digits of extension number

        if is_last:
            # Last extension becomes default catch-all for external profile
            blocks.append(f"""\
    <!-- VVP Inbound default -> extension {ext.ext} ({xml_escape(ext.description) or 'default'}) -->
    <extension name="vvp-inbound-{ext.ext}">
      <condition field="${{sofia_profile_name}}" expression="^external$">
        <action application="log" data="INFO [VVP] Inbound PSTN call to {ext.ext} from ${{caller_id_number}}"/>
        <action application="set" data="vvp_brand_name=Test Corporation Ltd"/>
        <action application="set" data="vvp_brand_logo=https://example.com/logo.png"/>
        <action application="set" data="vvp_status=VALID"/>
        <action application="set" data="sip_h_X-VVP-Brand-Name=${{vvp_brand_name}}"/>
        <action application="set" data="sip_h_X-VVP-Brand-Logo=${{vvp_brand_logo}}"/>
        <action application="set" data="sip_h_X-VVP-Status=${{vvp_status}}"/>
        <action application="export" data="nolocal:sip_h_X-VVP-Brand-Name=${{vvp_brand_name}}"/>
        <action application="export" data="nolocal:sip_h_X-VVP-Brand-Logo=${{vvp_brand_logo}}"/>
        <action application="export" data="nolocal:sip_h_X-VVP-Status=${{vvp_status}}"/>
        <action application="ring_ready"/>
        <action application="set" data="hangup_after_bridge=true"/>
        <action application="set" data="continue_on_fail=true"/>
        <action application="bridge" data="user/{ext.ext}@pbx.rcnx.io"/>
        <action application="log" data="WARNING [VVP] Bridge to {ext.ext} failed"/>
        <action application="answer"/>
        <action application="playback" data="ivr/ivr-call_cannot_be_completed_as_dialed.wav"/>
        <action application="hangup" data="USER_BUSY"/>
      </condition>
    </extension>
""")
        else:
            # Specific TN match for non-default extensions
            # Use the CLI to derive the TN pattern (extract last digits)
            blocks.append(f"""\
    <!-- VVP Inbound to {xml_escape(ext.cli)} -> extension {ext.ext} ({xml_escape(ext.description)}) -->
    <extension name="vvp-inbound-{ext.ext}">
      <condition field="${{sofia_profile_name}}" expression="^external$"/>
      <condition field="destination_number" expression="^\\+?4419233110{ext_suffix}$">
        <action application="log" data="INFO [VVP] Inbound PSTN call to {ext.ext} from ${{caller_id_number}}"/>
        <action application="set" data="vvp_brand_name=Test Corporation Ltd"/>
        <action application="set" data="vvp_brand_logo=https://example.com/logo.png"/>
        <action application="set" data="vvp_status=VALID"/>
        <action application="set" data="sip_h_X-VVP-Brand-Name=${{vvp_brand_name}}"/>
        <action application="set" data="sip_h_X-VVP-Brand-Logo=${{vvp_brand_logo}}"/>
        <action application="set" data="sip_h_X-VVP-Status=${{vvp_status}}"/>
        <action application="export" data="nolocal:sip_h_X-VVP-Brand-Name=${{vvp_brand_name}}"/>
        <action application="export" data="nolocal:sip_h_X-VVP-Brand-Logo=${{vvp_brand_logo}}"/>
        <action application="export" data="nolocal:sip_h_X-VVP-Status=${{vvp_status}}"/>
        <action application="ring_ready"/>
        <action application="set" data="hangup_after_bridge=true"/>
        <action application="set" data="continue_on_fail=true"/>
        <action application="bridge" data="user/{ext.ext}@pbx.rcnx.io"/>
        <action application="log" data="WARNING [VVP] Bridge to {ext.ext} failed"/>
        <action application="answer"/>
        <action application="playback" data="ivr/ivr-call_cannot_be_completed_as_dialed.wav"/>
        <action application="hangup" data="USER_BUSY"/>
      </condition>
    </extension>
""")

    return "\n".join(blocks)
